### ISSUE TITLE
java.io.File.getName()

### ISSUE THREAD

**Issue by SwordOfSouls** [VolmitSoftware/BileTools#6]
So I'm trying to use bile tools: https://www.spigotmc.org/resources/biletools-test-plugins-faster.54823/

But am getting this error (Windows):
```
[BileTools] Task #2 for BileTools v2 generated an exception
java.lang.NullPointerException: Cannot invoke "java.io.File.getName()" because the return value of "com.volmit.bile.BileUtils.getPluginFile(org.bukkit.plugin.Plugin)" is null
        at com.volmit.bile.BileTools.onTick(BileTools.java:457) ~[BileTools-2.jar:?]
        at com.volmit.bile.BileTools$2.run(BileTools.java:324) ~[BileTools-2.jar:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-346]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Paper-346]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1564) ~[patched_1.17.1.jar:git-Paper-346]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:490) ~[patched_1.17.1.jar:git-Paper-346]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1480) ~[patched_1.17.1.jar:git-Paper-346]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1279) ~[patched_1.17.1.jar:git-Paper-346]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-346]
        at java.lang.Thread.run(Thread.java:831) ~[?:?]
```
The plugin still reloads the jar but still gets this error for some reason.

**Comment by xNasuni** [comment]
same

**Comment by Stephcraft** [comment]
I also get this error from time to time.
